version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/server

permission:
  - object: /
   pattern: "**"
   owner: ec2-user
   group: ec2-user
hooks:
  BeforeInstall:
    - location: server_clear.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: server_clear.sh
      timeout: 300
      runas: ec2-user
  ApplicattionStart:
    - location: server_start.sh
      timeout: 300
      runas: ec2-user
  ApplicattionStop:
    - location: server_stop.sh
      timeout: 300
      runas: ec2-user