version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
      - echo $CODEBUILD_SRC_DIR
artifacts:
  files:
    - target/cargo-mail.jar
  discard-paths: yes